package ru.sber.cargotech.claim.dto;

import ru.sber.cargotech.claim.enums.ClaimStatus;
import ru.sber.cargotech.claim.enums.ClaimType;
import ru.sber.cargotech.claim.enums.DocumentValidationStatus;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

public record ClaimDetailsResponse(
    UUID id,
    UUID organizationId,
    String claimNumber,
    ClaimType claimType,
    ClaimStatus status,
    String reason,
    String recipientName,
    String recipientEmail,
    String recipientAddress,
    String bankDetails,
    Integer responseDeadlineDays,
    String signerFullName,
    String signerPosition,
    String signerAuthority,
    UUID shipmentId,
    String shipmentNumber,
    UUID contractId,
    String contractNumber,
    UUID creditorId,
    String creditorName,
    UUID debtorId,
    String debtorName,
    BigDecimal principalDebt,
    BigDecimal penaltyAmount,
    BigDecimal totalAmount,
    boolean nonPaymentConfirmed,
    OffsetDateTime nonPaymentConfirmedAt,
    UUID nonPaymentConfirmedBy,
    String nonPaymentConfirmationComment,
    OffsetDateTime nonPaymentConfirmationRequestedAt,
    UUID nonPaymentConfirmationRequestedBy,
    DocumentValidationStatus documentValidationStatus,
    String documentValidationErrors,
    boolean manualReviewRequired,
    String manualReviewReason,
    String usedSources,
    OffsetDateTime validationOverriddenAt,
    UUID validationOverriddenBy,
    String validationOverrideReason,
    UUID assignedLawyerId,
    UUID finalVersionId,
    UUID lastPaymentCheckId,
    OffsetDateTime approvedAt,
    UUID approvedBy,
    OffsetDateTime sentAt,
    OffsetDateTime paidAt,
    OffsetDateTime cancelledAt,
    String cancellationReasonCode,
    String cancellationReason,
    OffsetDateTime escalatedAt,
    OffsetDateTime createdAt,
    UUID createdBy,
    OffsetDateTime updatedAt,
    UUID updatedBy
) {
}
