package ru.sber.cargotech.claim.enums;

public enum ContractExtractionField {
    CONTRACT_NUMBER,
    SIGNED_AT,
    PAYMENT_DAYS,
    PAYMENT_DAY_TYPE,
    PAYMENT_START_EVENT,
    PAYMENT_SCHEDULE_TYPE,
    PAYMENT_WEEK_DAYS,
    PENALTY_TYPE,
    PENALTY_RATE,
    CLAIM_RESPONSE_DAYS,
    CLAIM_RESPONSE_DAY_TYPE,
    JURISDICTION,
    EXACT_CLAUSE
}
