server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: payment

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cargotech}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: cargotech
        jdbc:
          time_zone: UTC

payment:
  security:
    jwt-secret-base64: ${JWT_SECRET_BASE64}
    jwt-issuer: ${JWT_ISSUER:http://localhost:8081}

services:
  claim:
    base-url: ${CLAIM_SERVICE_URL:http://localhost:8083}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    persist-authorization: true
    try-it-out-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info